### ISSUE TITLE
Validation error on an invoice white note line

### ISSUE THREAD

**Issue by JulienC22** [OCA/l10n-portugal#110]
## Module
Technical name : l10n_pt_vat
Version : 14.0.1.0.2

## Describe the bug
on an invoice to which I added a note, when I validate it, I get the following error message : A tax exemption reason must be provided.
It seems that the module expects a tax on each of the lines of the invoice (title and note also)

1. create a manual invoice
2. add a note line in the invoice lines
3. validate the invoice

**Expected behavior**
do not take into account the title and note lines when validating an invoice by this module

**Comment by dreispt** [comment]
This was fixed by this commit:
ec543bd 2024-04-17 | fix: do not throw error if the line is a note or a section [Simon COLLIN]
