### ISSUE TITLE
Integração com InvoiceExpress e SAFT-PT de Contabilidad

### ISSUE THREAD

**Issue by jvbp** [OCA/l10n-portugal#47]
Bom dia Daniel,

Uma duvida que temos em nossa empresa é como as empresas que utlizam Odoo em Portugal fazem para obter o fichero SAFT-PT de Contabilidade que passa a ser obrigatorio a partir de 2022.

Você sabe se o InvoiceExpress esta preparado para isso?

Obrigado.

**Comment by SIC-pmrteixeira** [comment]
Boa tarde,
Julgo que o InvoiceExpress não disponibiliza o SAFT de contabilidade, apenas o de facturação.

As empresas com contabilidade organizada frequentemente externalizam este serviço, pelo que o SAFT de contabilidade é gerado pelos contabilistas no seu software.

Há empresas em Portugal que já estão fazendo contabilidade em Odoo e como tal gerando o seu SAFT de contabilidade, se necessitar de ajuda fale com a Smart Improve Consulting.

Esta APP desenvolvida pelo Daniel permite integrar com o InvoiceXpress e através dele gerar SAFT de facturação e comunicação de documentos de transporte.

Espero ter ajudado,
PT

**Comment by thinkopen-pt** [comment]
Boa tarde a todos,

Complemento também o exposto que no caso de implementações de contabilidade
PT com Odoo, poderão também entrar em contacto connosco /ThinkOpen).
Damos resposta a todas as necessidades dessa área, estando a mesma já em
processo de certificação SVAT por parte da Autoridade Tributária.
A contabilidade PT by ThinkOpen é também utilizada pelo ISCAL há já 2 anos,
na componente prática das cadeiras de contabilidade.

Qualquer questão sobre o tema disponham.

Obrigado,

Luis Brito Antunes

Managing Partner / CEO
<+351919021428> +351 919 021 428 <+351919021428> <+351808455255> 808 455 255
<+351808455255> Avenida das Túlipas, 6º 13º A/B | 1465-161 Algés
<https://thinkopen.solutions/> <https://www.facebook.com/ThinkOpenSolutions>
<https://twitter.com/thinkopenTW>
<https://www.linkedin.com/company/thinkopen-solutions?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2232083%2Cidx%3A4-1-5%2CtarId%3A1467817206116%2Ctas%3Athinkopen%20solutions>


'Pedro Teixeira' via Sysadmins ***@***.***> escreveu no
dia quinta, 9/09/2021 à(s) 16:42:

**Comment by dreispt** [comment]
@jvbp Bom dia, as respostas anteriores estão corretas.

O InvoiceXpress apenas cobre a componente de faturação certificada, e não o SAFT de contabilidade.
Acresce que tanto a Community Edition (CE) como a Enterprise Edition (EE) estão longe de conseguir suportar o SAFT de Contabilidade, pelo que lamento mas é algo que não acontecerá em breve.

Alguns integradores, como a ThinkOpen, têm serviços cloud  disponíveis, com uma versão de Odoo modificada que tem a certificação que permite a geração do SAFT Contabilidade.
