### ISSUE TITLE
New branch: 9.0

### ISSUE THREAD

**Issue by andreparames** [OCA/l10n-portugal#6]
We're looking to update one of our PRs to submit a new module targeting Odoo v9, but Github only allows PRs for existing branches, so we request that a new branch be created for 9.0.

**Comment by pedrobaeza** [comment]
The new branch will be created in days. We are finishing the script that makes the mass-upgrade here: https://github.com/OCA/maintainer-tools/pull/141

**Comment by andreparames** [comment]
OK, thank you.
