### ISSUE TITLE
Product price VAT included

### ISSUE THREAD

**Issue by ferreira84** [OCA/l10n-portugal#72]
When you work with VAT included in the price. 
Confirm the invoice, it is created in invoicexpress, however invoicexpress will add vat to the included vat amount sent by odoo. 

So it is not possible to use the module with vat prices included. Any help on this.

**Comment by FelixLumen** [comment]
I have the same problem. Did you find any solution?

**Comment by FelixLumen** [comment]
Can anybody help to fix this? I would also pay for this fix.
