### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-portugal#75]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] l10n_pt_vat

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by Fmartinsz** [comment]
I will be doing the migration of this module **l10n_pt_vat**

**Comment by Fmartinsz** [comment]
Hey, I noticed this issue is still up so maybe it was forgotten about, but the migration was finished a few months ago and the PR was accepted.
