### ISSUE TITLE
[14.0][15.0][16.0] git checkout on windows "" error: invalid path  'l10n_pt_vat/static/description/Autoridade-tributaria-e-Aduaneira-ATA-420x420.png:Zone.Identifier' ""

### ISSUE THREAD

**Issue by rpinset** [OCA/l10n-portugal#99]
## Module
l10n_pt_vat

## Describe the bug
When I git checkout on windows (for Docker environment) "" error: invalid path  'l10n_pt_vat/static/description/Autoridade-tributaria-e-Aduaneira-ATA-420x420.png:Zone.Identifier'
"" because file has got a ":" space after ".png"
https://github.com/OCA/l10n-portugal/blob/16.0/l10n_pt_vat/static/description/Autoridade-tributaria-e-Aduaneira-ATA-420x420.png%3AZone.Identifier

## To Reproduce
**Affected versions**: 14.0 15.0 16.0

1. On windows
2. Git clone this repo
3. git checkout 14.0

**Comment by dreispt** [comment]
This should be fixed now.
